version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=your-username
      - DB_PASSWORD=your-password
      - DB_DATABASE=your-database
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: your-username
      POSTGRES_PASSWORD: your-password
      POSTGRES_DB: your-database
    ports:
      - "5432:5432"